from __future__ import annotations

from typing import Any

from chanta_core.self_awareness.conformance import SelfAwarenessConformanceService
from chanta_core.self_awareness.mapping import (
    SELF_AWARENESS_OCEL_EVENT_TYPES,
    SELF_AWARENESS_OCEL_MAPPING,
    SELF_AWARENESS_OCEL_OBJECT_TYPES,
    SELF_AWARENESS_OCEL_RELATION_TYPES,
)
from chanta_core.self_awareness.registry import SelfAwarenessRegistryService


class SelfAwarenessReportService:
    def __init__(
        self,
        *,
        registry_service: SelfAwarenessRegistryService | None = None,
        conformance_service: SelfAwarenessConformanceService | None = None,
    ) -> None:
        self.registry_service = registry_service or SelfAwarenessRegistryService()
        self.conformance_service = conformance_service or SelfAwarenessConformanceService(self.registry_service)

    def build_pig_report(self) -> dict[str, Any]:
        contracts = self.registry_service.list_contracts()
        conformance = self.conformance_service.run_conformance()
        safety_counts = {
            "dangerous_capability_count": conformance.dangerous_capability_count,
            "write_mutation_count": conformance.workspace_mutation_count,
            "shell_usage_count": conformance.shell_usage_count,
            "network_usage_count": conformance.network_usage_count,
            "mcp_usage_count": conformance.mcp_usage_count,
            "plugin_loading_count": conformance.plugin_loading_count,
            "external_harness_execution_count": conformance.external_harness_execution_count,
            "memory_mutation_count": conformance.memory_mutation_count,
            "persona_mutation_count": conformance.persona_mutation_count,
            "overlay_mutation_count": conformance.overlay_mutation_count,
        }
        return {
            "report_name": "Self-Awareness Layer PIG Report",
            "version": "0.20.9",
            "layer": "self_awareness",
            "state": "self_awareness_foundation_v1_consolidated",
            "definition": "Read-only self-awareness foundation v1 consolidated release unit for workspace boundary, metadata inventory, bounded text perception, bounded literal search, deterministic structure summaries, project surface candidates, deterministic surface verification reports, candidate-only directed intention bundles, read-only operator workbench snapshots, and release-readiness closure.",
            "contract_count": len(contracts),
            "contract_ids": [item.skill_id for item in contracts],
            "workspace_awareness_coverage": {
                "path_verification": "implemented",
                "workspace_inventory": "implemented",
                "text_read": "implemented_limited_preview",
                "workspace_search": "implemented_bounded_literal",
                "python_symbols": "implemented_deterministic",
                "markdown_structure": "implemented_deterministic",
                "shallow_key_summary": "helper_deterministic",
                "symbol_scan": "not_implemented",
                "summary": "not_implemented",
                "project_structure": "implemented_surface_snapshot",
                "config_surface": "candidate_helper_only",
                "test_surface": "candidate_helper_only",
                "surface_verification": "implemented_evidence_boundary_candidate_checks",
                "directed_intention_candidate": "implemented_candidate_only",
                "workbench": "implemented_read_only_operator_surface",
                "consolidation": "implemented_release_closure",
                "project_semantic_inspection": "not_implemented",
            },
            "workbench": "implemented_read_only_operator_surface",
            "consolidation": "implemented_release_closure",
            "read_only_self_awareness_v1": "warning",
            "self_modification": "not_started",
            "self_execution": "not_started",
            "external_contact": "not_started",
            "growth_bridge": "not_started",
            "read_only": True,
            "mutation_performed": False,
            "approval_enabled": False,
            "promotion_enabled": False,
            "llm_summary_enabled": False,
            "llm_architecture_inference_enabled": False,
            "dependency_graph_enabled": False,
            "runtime_introspection_enabled": False,
            "llm_judge_enabled": False,
            "llm_planner_enabled": False,
            "test_execution_enabled": False,
            "shell_execution_enabled": False,
            "execution_enabled": False,
            "materialization_enabled": False,
            "auto_task_creation_enabled": False,
            "todo_file_write_enabled": False,
            "memory_mutation_enabled": False,
            "persona_mutation_enabled": False,
            "overlay_mutation_enabled": False,
            "canonical_promotion_enabled": False,
            "safety_boundary_counts": safety_counts,
            "diagnostics": conformance.to_dict(),
            "recommendation": (
                "Self-Awareness Foundation v1 consolidated; proceed only to future safety tracks without claiming execution or self-modification."
                if conformance.passed
                else "Do not close Self-Awareness Foundation v1 until self-awareness conformance failures are fixed."
            ),
            "implemented_skill_ids": [
                "skill:self_awareness_workspace_inventory",
                "skill:self_awareness_path_verify",
                "skill:self_awareness_text_read",
                "skill:self_awareness_workspace_search",
                "skill:self_awareness_markdown_structure",
                "skill:self_awareness_python_symbols",
                "skill:self_awareness_project_structure",
                "skill:self_awareness_surface_verify",
                "skill:self_awareness_plan_candidate",
                "skill:self_awareness_todo_candidate",
            ],
            "effect_type": "read_only_observation",
            "skills_executed": False,
            "canonical_store": "ocel",
        }

    def build_ocpx_projection(self) -> dict[str, Any]:
        conformance = self.conformance_service.run_conformance()
        return {
            "projection_name": "Self-Awareness Layer OCPX Projection",
            "version": "0.20.9",
            "layer": "self_awareness",
            "state": "self_awareness_foundation_v1_consolidated",
            "release_version": "v0.20.9",
            "object_coverage": list(SELF_AWARENESS_OCEL_OBJECT_TYPES),
            "event_coverage": list(SELF_AWARENESS_OCEL_EVENT_TYPES),
            "relation_coverage": list(SELF_AWARENESS_OCEL_RELATION_TYPES),
            "workspace_awareness_state": {
                "path_verification": "implemented",
                "workspace_inventory": "implemented",
                "text_read": "implemented_limited_preview",
                "workspace_search": "implemented_bounded_literal",
                "markdown_structure": "implemented_deterministic",
                "python_symbols": "implemented_deterministic",
                "shallow_key_summary": "helper_deterministic",
                "project_structure": "implemented_surface_snapshot",
                "config_surface": "candidate_helper_only",
                "test_surface": "candidate_helper_only",
                "surface_verification": "implemented_evidence_boundary_candidate_checks",
                "directed_intention_candidate": "implemented_candidate_only",
                "workbench": "implemented_read_only_operator_surface",
                "consolidation": "implemented_release_closure",
                "summary": "not_implemented",
                "project_semantic_inspection": "not_implemented",
            },
            "candidate_types": [
                "summary_candidate",
                "project_structure_candidate",
                "project_surface_candidate",
                "surface_verification_report",
                "plan_candidate",
                "todo_candidate",
                "no_action_candidate",
                "needs_more_input_candidate",
                "directed_intention_candidate_bundle",
                "consolidation_report",
            ],
            "read_model_types": [
                "self_awareness_workbench_snapshot",
                "self_awareness_coverage_row",
                "self_awareness_candidate_queue_view",
                "self_awareness_verification_queue_view",
                "self_awareness_safety_boundary_status",
            ],
            "effect_types": ["read_only_observation", "state_candidate_created"],
            "effect_type": "read_only_observation",
            "release_status": "releasable_with_warnings",
            "coverage_counts": {
                "object_type_count": len(SELF_AWARENESS_OCEL_OBJECT_TYPES),
                "event_type_count": len(SELF_AWARENESS_OCEL_EVENT_TYPES),
                "relation_type_count": len(SELF_AWARENESS_OCEL_RELATION_TYPES),
            },
            "mapping": SELF_AWARENESS_OCEL_MAPPING.to_dict(),
            "conformance_status": conformance.status,
            "skills_executed": False,
            "canonical_store": "ocel",
        }

    def render_pig_report_cli(self) -> str:
        report = self.build_pig_report()
        counts = report["safety_boundary_counts"]
        lines = [
            "Self-Awareness PIG Report",
            "layer=self_awareness",
            f"state={report['state']}",
            f"contract_count={report['contract_count']}",
            "workspace_path_verify=implemented",
            "workspace_inventory=implemented",
            "text_read=implemented_limited_preview",
            "workspace_search=implemented_bounded_literal",
            "markdown_structure=implemented_deterministic",
            "python_symbols=implemented_deterministic",
            "shallow_key_summary=helper_deterministic",
            "project_structure=implemented_surface_snapshot",
            "surface_verification=implemented_evidence_boundary_candidate_checks",
            "directed_intention_candidate=implemented_candidate_only",
            "workbench=implemented_read_only_operator_surface",
            "consolidation=implemented_release_closure",
            "config_surface=candidate_helper_only",
            "test_surface=candidate_helper_only",
            "read_only=true",
            "mutation_performed=false",
            "approval_enabled=false",
            "promotion_enabled=false",
            "read_only_self_awareness_v1=warning",
            "self_modification=not_started",
            "self_execution=not_started",
            "external_contact=not_started",
            "growth_bridge=not_started",
            "llm_summary_enabled=false",
            "llm_architecture_inference_enabled=false",
            "dependency_graph_enabled=false",
            "runtime_introspection_enabled=false",
            "llm_judge_enabled=false",
            "llm_planner_enabled=false",
            "test_execution_enabled=false",
            "shell_execution_enabled=false",
            "execution_enabled=false",
            "materialization_enabled=false",
            "auto_task_creation_enabled=false",
            "todo_file_write_enabled=false",
            "memory_mutation_enabled=false",
            "persona_mutation_enabled=false",
            "overlay_mutation_enabled=false",
            "canonical_promotion_enabled=false",
            "summary=not_implemented",
            f"dangerous_capability_count={counts['dangerous_capability_count']}",
            f"write_mutation_count={counts['write_mutation_count']}",
            f"shell_usage_count={counts['shell_usage_count']}",
            f"network_usage_count={counts['network_usage_count']}",
            f"mcp_usage_count={counts['mcp_usage_count']}",
            f"plugin_loading_count={counts['plugin_loading_count']}",
            f"external_harness_execution_count={counts['external_harness_execution_count']}",
            f"memory_mutation_count={counts['memory_mutation_count']}",
            f"persona_mutation_count={counts['persona_mutation_count']}",
            f"overlay_mutation_count={counts['overlay_mutation_count']}",
            f"recommendation={report['recommendation']}",
        ]
        return "\n".join(lines)

    def render_ocpx_projection_cli(self) -> str:
        projection = self.build_ocpx_projection()
        counts = projection["coverage_counts"]
        lines = [
            "Self-Awareness OCPX Projection",
            "layer=self_awareness",
            f"state={projection['state']}",
            "path_verification=implemented",
            "workspace_inventory=implemented",
            "text_read=implemented_limited_preview",
            "workspace_search=implemented_bounded_literal",
            "markdown_structure=implemented_deterministic",
            "python_symbols=implemented_deterministic",
            "project_structure=implemented_surface_snapshot",
            "surface_verification=implemented_evidence_boundary_candidate_checks",
            "directed_intention_candidate=implemented_candidate_only",
            "candidate_types=summary_candidate,project_structure_candidate,project_surface_candidate,surface_verification_report,plan_candidate,todo_candidate,no_action_candidate,needs_more_input_candidate,directed_intention_candidate_bundle,consolidation_report",
            "read_model_types=self_awareness_workbench_snapshot,self_awareness_coverage_row,self_awareness_candidate_queue_view,self_awareness_verification_queue_view,self_awareness_safety_boundary_status",
            "effect_types=read_only_observation,state_candidate_created",
            "release_version=v0.20.9",
            "release_status=releasable_with_warnings",
            f"object_type_count={counts['object_type_count']}",
            f"event_type_count={counts['event_type_count']}",
            f"relation_type_count={counts['relation_type_count']}",
            f"conformance_status={projection['conformance_status']}",
            "canonical_store=ocel",
        ]
        return "\n".join(lines)
